/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ibdzxuctzlixghnfbhjl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZHp4dWN0emxpeGdobmZiaGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMDYwMjQsImV4cCI6MjA3NTY4MjAyNH0.PW3Xa44d7efHu-kTFw-qhZDpHITTVbtoTdE5XO1O2tQ"